// <auto-generated />
using System;
using DreamScapeInteractive;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamScapeInteractive.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250218122243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("MagicPropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MagicPropertyId");

                    b.HasIndex("TypeId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "It feels weirdly cool to the touch",
                            Durability = 99,
                            MagicPropertyId = 10,
                            Name = "Burning Sword of Damnation",
                            Power = 40,
                            Rarity = 50,
                            Speed = 10,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Its blade glistens with eternal frost",
                            Durability = 80,
                            MagicPropertyId = 7,
                            Name = "Frozen Dagger of the North",
                            Power = 25,
                            Rarity = 60,
                            Speed = 35,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "It radiates warmth and whispers of ancient knowledge",
                            Durability = 70,
                            MagicPropertyId = 3,
                            Name = "Staff of the Eternal Sun",
                            Power = 55,
                            Rarity = 90,
                            Speed = 5,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Its surface reflects the memories of fallen heroes",
                            Durability = 120,
                            MagicPropertyId = 5,
                            Name = "Shield of the Forgotten King",
                            Power = 10,
                            Rarity = 75,
                            Speed = -5,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Wearing it feels like slipping into the darkness itself",
                            Durability = 50,
                            MagicPropertyId = 9,
                            Name = "Ring of Shadows",
                            Power = 15,
                            Rarity = 85,
                            Speed = 20,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "The bowstring hums with a mournful song",
                            Durability = 60,
                            MagicPropertyId = 11,
                            Name = "Cursed Bow of the Phantom",
                            Power = 30,
                            Rarity = 65,
                            Speed = 40,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Its gem pulses with the energy of distant stars",
                            Durability = 40,
                            MagicPropertyId = 6,
                            Name = "Amulet of the Starcaller",
                            Power = 20,
                            Rarity = 95,
                            Speed = 10,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "You feel lighter just by wearing them",
                            Durability = 45,
                            MagicPropertyId = 4,
                            Name = "Boots of the Windwalker",
                            Power = 5,
                            Rarity = 55,
                            Speed = 50,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Whispers of ancient minds fill your ears",
                            Durability = 85,
                            MagicPropertyId = 6,
                            Name = "Helmet of Echoing Thoughts",
                            Power = 8,
                            Rarity = 70,
                            Speed = 2,
                            TypeId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "The pages are blank, but you hear them screaming",
                            Durability = 30,
                            MagicPropertyId = 10,
                            Name = "Tome of the Abyss",
                            Power = 65,
                            Rarity = 100,
                            Speed = 0,
                            TypeId = 10
                        });
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sword"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dagger"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shield"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ring"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bow"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Amulet"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Boots"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Helmet"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tome"
                        });
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Magic_Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MagicProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flame Enchantment",
                            Value = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Frostbite Aura",
                            Value = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Storm Surge",
                            Value = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "Windwalker’s Grace",
                            Value = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stoneheart Barrier",
                            Value = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shadow Cloak",
                            Value = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Venomous Touch",
                            Value = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Radiant Blessing",
                            Value = 5
                        },
                        new
                        {
                            Id = 9,
                            Name = "Timewarp Echo",
                            Value = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Abyssal Curse",
                            Value = 6
                        },
                        new
                        {
                            Id = 11,
                            Name = "Abyssal Curses",
                            Value = 8
                        });
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserItem1Id")
                        .HasColumnType("int");

                    b.Property<int>("UserItem2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserItem1Id");

                    b.HasIndex("UserItem2Id");

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending",
                            TradeDate = new DateTime(2025, 2, 18, 13, 22, 43, 122, DateTimeKind.Local).AddTicks(6869),
                            UserItem1Id = 1,
                            UserItem2Id = 2
                        },
                        new
                        {
                            Id = 2,
                            Status = "Completed",
                            TradeDate = new DateTime(2025, 2, 17, 13, 22, 43, 122, DateTimeKind.Local).AddTicks(6929),
                            UserItem1Id = 2,
                            UserItem2Id = 3
                        },
                        new
                        {
                            Id = 3,
                            Status = "Cancelled",
                            TradeDate = new DateTime(2025, 2, 16, 13, 22, 43, 122, DateTimeKind.Local).AddTicks(6934),
                            UserItem1Id = 4,
                            UserItem2Id = 5
                        });
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "seeker@dreamscape.com",
                            HashedPassword = "x23QkAqeU+9b0ybcjfg3h2ScmMSAc1DTBuC+WE2XQC0=:bbjEEquFZMHKfIIQ+cvK2g==:10000:SHA512",
                            IsAdmin = true,
                            Username = "DreamSeeker"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "wanderer@dreamscape.com",
                            HashedPassword = "LrU9t6phK7+r7ihcWD36kaiWN6EFP4vx4DAbu9Bk5Bs=:jLLnmlBpK+O9l71RQo/3lw==:10000:SHA512",
                            IsAdmin = false,
                            Username = "StarWanderer"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "guardian@dreamscape.com",
                            HashedPassword = "3uhLhDIwMQUDpsGS6oLCp3BRdBIpRh8/Z3P+L+gSXyU=:kMEEhG9pd+96x11u/vik2Q==:10000:SHA512",
                            IsAdmin = false,
                            Username = "MysticGuardian"
                        },
                        new
                        {
                            Id = 4,
                            EmailAddress = "walker@dreamscape.com",
                            HashedPassword = "yogKZUvtDr+1O24cCnCZaHGXKg5MNSDVUMYuhnG7dKg=:qwmS/3Y2Y5JVg1FinophPA==:10000:SHA512",
                            IsAdmin = false,
                            Username = "ShadowWalker"
                        },
                        new
                        {
                            Id = 5,
                            EmailAddress = "luna@dreamscape.com",
                            HashedPassword = "Mu9y5nh4s5wg2TflHgmdElfebIXhWPXUvvkaU0jBlD8=:yjdmG3cnskOMw0TGwprilg==:10000:SHA512",
                            IsAdmin = false,
                            Username = "LunaCaller"
                        });
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.UserItem", b =>
                {
                    b.Property<int>("UserItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserItems");

                    b.HasData(
                        new
                        {
                            UserItemId = 1,
                            ItemId = 1,
                            Quantity = 20,
                            UserId = 1
                        },
                        new
                        {
                            UserItemId = 2,
                            ItemId = 2,
                            Quantity = 10,
                            UserId = 2
                        },
                        new
                        {
                            UserItemId = 3,
                            ItemId = 3,
                            Quantity = 5,
                            UserId = 3
                        },
                        new
                        {
                            UserItemId = 4,
                            ItemId = 4,
                            Quantity = 15,
                            UserId = 4
                        },
                        new
                        {
                            UserItemId = 5,
                            ItemId = 5,
                            Quantity = 3,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Item", b =>
                {
                    b.HasOne("DreamScapeInteractive.Data.Classes.Magic_Property", "MagicProperty")
                        .WithMany("Items")
                        .HasForeignKey("MagicPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamScapeInteractive.Data.Classes.ItemType", "Type")
                        .WithMany("Items")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MagicProperty");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Trade", b =>
                {
                    b.HasOne("DreamScapeInteractive.Data.Classes.User", null)
                        .WithMany("Trades")
                        .HasForeignKey("UserId");

                    b.HasOne("DreamScapeInteractive.Data.Classes.UserItem", "UserItem1")
                        .WithMany()
                        .HasForeignKey("UserItem1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamScapeInteractive.Data.Classes.UserItem", "UserItem2")
                        .WithMany()
                        .HasForeignKey("UserItem2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserItem1");

                    b.Navigation("UserItem2");
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.UserItem", b =>
                {
                    b.HasOne("DreamScapeInteractive.Data.Classes.Item", "Item")
                        .WithMany("UserItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamScapeInteractive.Data.Classes.User", "User")
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Item", b =>
                {
                    b.Navigation("UserItems");
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.ItemType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.Magic_Property", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DreamScapeInteractive.Data.Classes.User", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
